"""Demo presets (schema-style requests). Scenarios adapted from rorshopping/jev-on-a-laptop (MIT License, (c) 2026 rorshopping)."""
PRESETS = [{'id': 'support_triage',
  'title': 'Enterprise Incident Triage & Routing (28 Fields)',
  'description': 'End-to-end multi-dimensional semantic analysis of a critical enterprise production outage ticket.',
  'context': 'SUPPORT TICKET #INC-44019\n'
             'From: Marcus Vance, CTO @ Omnicorp Global (Tier 1 Strategic Enterprise, k ARR)\n'
             'Subject: CRITICAL P0: Production US-East API 502 Gateway Outage - Checkout Down\n'
             '\n'
             'Body: Our primary checkout service has been failing completely for the last 48 minutes because your US-East API endpoint is '
             'throwing 502 Bad Gateway errors on every POST /v2/charges call. We are losing approximately ,000 in transaction revenue '
             'every ten minutes!\n'
             '\n'
             'Furthermore, our billing audit discovered this morning that your platform double-billed our corporate account for data '
             'overages (,800 improper charge on Invoice #INV-8812).\n'
             '\n'
             'If this API outage is not resolved within 30 minutes, our legal counsel will formally issue notice of material breach of our '
             '99.99% availability SLA and initiate contract termination with full damages. We demand an immediate phone bridge with your '
             'VP of Engineering and a full refund of the bogus invoice.\n'
             '\n'
             'Environment: PRODUCTION\n'
             'Affected Cluster: us-east-1a\n'
             'Account Priority: STRATEGIC_TIER_1',
  'schema': {'sentiment': {'type': 'enum',
                           'description': 'Customer emotional state',
                           'choices': ['VERY_NEGATIVE', 'NEGATIVE', 'NEUTRAL', 'POSITIVE']},
             'severity_tier': {'type': 'enum',
                               'description': 'Contractual incident severity tier',
                               'choices': ['SEV_0_CRITICAL', 'SEV_1_MAJOR', 'SEV_2_MODERATE', 'SEV_3_MINOR']},
             'primary_department': {'type': 'enum',
                                    'description': 'Primary internal department to resolve',
                                    'choices': ['INFRASTRUCTURE_SRE',
                                                'BILLING_FINANCE',
                                                'SECURITY_OPS',
                                                'LEGAL_COMPLIANCE',
                                                'ENTERPRISE_SUCCESS']},
             'secondary_department': {'type': 'enum',
                                      'description': 'Secondary coordinating department',
                                      'choices': ['DATABASE_TEAM', 'NETWORK_OPS', 'CORE_API', 'IDENTITY_AUTH', 'NONE']},
             'sla_breach_risk': {'type': 'boolean', 'description': 'Whether contractual uptime SLA is at immediate risk'},
             'requires_executive_escalation': {'type': 'boolean', 'description': 'Whether VP/Exec team must be alerted immediately'},
             'can_resolve_autonomously': {'type': 'boolean',
                                          'description': 'Whether automated runbook can resolve without human intervention'},
             'confidence_above_auto_threshold': {'type': 'boolean',
                                                 'description': 'Whether system decision confidence exceeds 95% threshold'},
             'churn_risk_level': {'type': 'enum',
                                  'description': 'Probability customer cancels contract',
                                  'choices': ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL_IMMINENT']},
             'refund_recommended': {'type': 'boolean', 'description': 'Whether a billing refund/credit should be issued'},
             'refund_tier': {'type': 'enum',
                             'description': 'Scale of recommended financial refund',
                             'choices': ['NONE', 'PARTIAL_CREDIT', 'FULL_MONTH_CREDIT', 'CUSTOM_COMPENSATION']},
             'requires_legal_review': {'type': 'boolean', 'description': 'Whether legal counsel must review breach claims'},
             'security_incident': {'type': 'boolean', 'description': 'Whether ticket indicates unauthorized security breach'},
             'compliance_breach': {'type': 'boolean', 'description': 'Whether regulatory compliance standard was violated'},
             'customer_tenure_tier': {'type': 'enum',
                                      'description': 'Customer contract classification',
                                      'choices': ['ENTERPRISE_STRATEGIC', 'MID_MARKET', 'GROWTH', 'EARLY_STAGE']},
             'root_cause_domain': {'type': 'enum',
                                   'description': 'Probable technical system domain of failure',
                                   'choices': ['DNS_ROUTING', 'DB_LOCKING', 'API_GATEWAY', 'BILLING_SYNC', 'AUTH_TOKEN_EXPIRY']},
             'target_resolution_hours': {'type': 'enum',
                                         'description': 'Target turnaround SLA window',
                                         'choices': ['1_HOUR', '4_HOURS', '12_HOURS', '24_HOURS']},
             'requires_phone_call': {'type': 'boolean', 'description': 'Whether emergency live bridge call is required'},
             'notify_account_executive': {'type': 'boolean', 'description': 'Whether dedicated enterprise AE should be paged'},
             'public_status_page_incident': {'type': 'boolean', 'description': 'Whether incident should be posted to public status page'},
             'postmortem_required': {'type': 'boolean', 'description': 'Whether formal RCA postmortem document must be authored'},
             'vendor_fault': {'type': 'boolean', 'description': 'Whether outage is confirmed due to our platform'},
             'contract_penalty_applicable': {'type': 'boolean', 'description': 'Whether customer has right to claim SLA penalty credits'},
             'escalate_to_vp': {'type': 'boolean', 'description': 'Whether VP of Engineering page is warranted'},
             'customer_sentiment_trend': {'type': 'enum',
                                          'description': 'Direction of customer relationship sentiment',
                                          'choices': ['WORSENING', 'STATIC', 'IMPROVING']},
             'suggested_action': {'type': 'enum',
                                  'description': 'Immediate first response workflow action',
                                  'choices': ['PAGE_ONCALL_SRE', 'ISSUE_CREDIT_MEMO', 'DISPATCH_SECURITY_TEAM', 'SCHEDULE_EXEC_CALL']},
             'assigned_agent_tier': {'type': 'enum',
                                     'description': 'Support engineer tier required',
                                     'choices': ['TIER_1', 'TIER_2', 'SENIOR_SRE', 'DIRECTOR']},
             'ticket_priority': {'type': 'enum',
                                 'description': 'Internal triage queue priority',
                                 'choices': ['P0_EMERGENCY', 'P1_HIGH', 'P2_NORMAL', 'P3_LOW']}}},
 {'id': 'code_security',
  'title': 'Autonomous Code Security & PR Vulnerability Triage (28 Fields)',
  'description': 'Automated SAST/DAST static analysis triage evaluating an enterprise pull request containing leaked secrets and injection '
                 'risks.',
  'context': 'CI/CD PIPELINE AUDIT #PR-10822\n'
             'Repository: payment-gateway-core\n'
             'Branch: feature/direct-stripe-integration -> main\n'
             'Author: external-contractor-92 (First PR submitted)\n'
             'Diff Summary: +482 lines, -12 lines in src/services/charge_processor.py and config/aws.env\n'
             '\n'
             'Static Scanner Findings:\n'
             '1. Hardcoded Plaintext AWS Root Secret: AWS_SECRET_ACCESS_KEY="AKIAIOSFODNN7EXAMPLE..." committed into config/aws.env\n'
             '2. Unsanitized SQL Query Concatenation: cursor.execute(f"SELECT * FROM users WHERE id = \'{req.user_id}\' AND secret = '
             '\'{req.token}\'")\n'
             "3. Insecure Deserialization: pickle.loads(base64.b64decode(req.headers['X-Payload'])) detected in webhook handler.\n"
             "4. Dependency Check: Added vulnerable PyPI package 'requests-oauthlib==0.4.0' with 3 critical CVEs.\n"
             '\n'
             'Deployment Target: PRODUCTION (us-west-2 Kubernetes Cluster)\n'
             'Compliance Scope: SOC2 Type II, PCI-DSS Level 1, HIPAA\n'
             'Security Gate Status: FAILED_BLOCKING',
  'schema': {'is_vulnerability': {'type': 'boolean', 'description': 'Whether pull request introduces severe security vulnerabilities'},
             'primary_cwe': {'type': 'enum',
                             'description': 'Primary vulnerability classification',
                             'choices': ['CWE_89_SQL_INJECTION',
                                         'CWE_798_HARDCODED_CREDENTIALS',
                                         'CWE_502_DESERIALIZATION',
                                         'CWE_20_IMPROPER_INPUT']},
             'secondary_cwe': {'type': 'enum',
                               'description': 'Secondary vulnerability indicator',
                               'choices': ['CWE_798_HARDCODED_CREDENTIALS',
                                           'CWE_1104_OUTDATED_COMPONENTS',
                                           'CWE_200_INFO_EXPOSURE',
                                           'NONE']},
             'severity_level': {'type': 'enum',
                                'description': 'Combined security severity tier',
                                'choices': ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']},
             'block_pull_request': {'type': 'boolean', 'description': 'Whether CI/CD merge should be immediately blocked'},
             'quarantine_branch': {'type': 'boolean', 'description': 'Whether git branch should be locked and quarantined'},
             'credential_revocation_required': {'type': 'boolean',
                                                'description': 'Whether AWS IAM credentials must be revoked immediately'},
             'requires_security_lead_signoff': {'type': 'boolean', 'description': 'Whether AppSec lead signature is required to unblock'},
             'exploitability_in_production': {'type': 'enum',
                                              'description': 'Production exploitability ease',
                                              'choices': ['REMOTE_UNAUTHENTICATED',
                                                          'AUTHENTICATED_USER',
                                                          'INTERNAL_NETWORK_ONLY',
                                                          'THEORETICAL']},
             'blast_radius': {'type': 'enum',
                              'description': 'Potential system impact scope',
                              'choices': ['FULL_AWS_ACCOUNT', 'DATABASE_COMPROMISE', 'CONTAINER_LOCAL', 'NONE']},
             'auto_generate_fix': {'type': 'boolean', 'description': 'Whether automated remediation patch should be PRed'},
             'remediation_effort': {'type': 'enum',
                                    'description': 'Estimated fix complexity',
                                    'choices': ['TRIVIAL_SECRETS_ROTATION', 'PARAMETRIZED_SQL_REFACTOR', 'MAJOR_ARCHITECTURE_CHANGE']},
             'pci_dss_impact': {'type': 'boolean', 'description': 'Whether findings trigger PCI-DSS compliance breach'},
             'soc2_audit_flag': {'type': 'boolean', 'description': 'Whether finding must be logged for annual SOC2 audit'},
             'hipaa_exposure_risk': {'type': 'boolean', 'description': 'Whether patient ePHI data is exposed'},
             'secret_type_detected': {'type': 'enum',
                                      'description': 'Specific secret credential leaked',
                                      'choices': ['AWS_ROOT_KEY', 'STRIPE_API_KEY', 'DATABASE_PASSWORD', 'NONE']},
             'target_environment': {'type': 'enum',
                                    'description': 'Destination deployment environment',
                                    'choices': ['PRODUCTION_CLUSTER', 'STAGING_ENVIRONMENT', 'LOCAL_DEV']},
             'notify_ciso': {'type': 'boolean', 'description': 'Whether CISO must be paged on mobile'},
             'requires_immediate_patch': {'type': 'boolean', 'description': 'Whether zero-day emergency patch window applies'},
             'jira_ticket_priority': {'type': 'enum',
                                      'description': 'Jira security queue priority',
                                      'choices': ['P0_BLOCKER', 'P1_CRITICAL', 'P2_MAJOR', 'P3_MINOR']},
             'assigned_team': {'type': 'enum',
                               'description': 'Primary team responsible for remediation',
                               'choices': ['APP_SEC_TEAM', 'INFRA_CLOUD_SEC', 'CORE_BACKEND', 'DEVOPS_PLATFORM']},
             'false_positive_risk': {'type': 'enum',
                                     'description': 'Likelihood of false positive scan finding',
                                     'choices': ['ALMOST_ZERO', 'LOW', 'MODERATE', 'HIGH']},
             'public_cve_match': {'type': 'boolean', 'description': 'Whether findings match known public CVE databases'},
             'auto_merge_allowed': {'type': 'boolean', 'description': 'Whether branch can merge under any circumstance'},
             'container_escape_risk': {'type': 'boolean',
                                       'description': 'Whether vulnerability allows Docker/Kubernetes container breakout'},
             'data_exfiltration_risk': {'type': 'enum',
                                        'description': 'Risk of bulk sensitive data theft',
                                        'choices': ['CATASTROPHIC', 'HIGH', 'MODERATE', 'NEGLIGIBLE']},
             'author_trust_score': {'type': 'enum',
                                    'description': 'Author risk profile evaluation',
                                    'choices': ['UNTRUSTED_EXTERNAL', 'NEW_EMPLOYEE', 'VERIFIED_STAFF', 'CORE_MAINTAINER']},
             'security_gate_status': {'type': 'enum',
                                      'description': 'Final policy engine disposition',
                                      'choices': ['FAILED_BLOCKING', 'WARNING_OVERRIDABLE', 'PASSED']}}},
 {'id': 'fintech_fraud',
  'title': 'FinTech Fraud & Autonomous AML Compliance (28 Fields)',
  'description': 'Real-time multi-attribute financial fraud detection, sanctions verification, and autonomous containment decision.',
  'context': 'TRANSACTION ALERT #TX-98421\n'
             'Timestamp: 2026-09-15 03:14:22 UTC\n'
             'Cardholder: Sarah Jenkins (Account ID: US-99120)\n'
             'Transaction Amount: ,850.00 USD\n'
             'Merchant: CyberGold Crypto Exchange (Nicosia, Cyprus)\n'
             'Cardholder Billing Address: Seattle, WA, USA\n'
             'Device IP: 185.220.101.5 (Known Tor Exit Node, Frankfurt, Germany)\n'
             'Device Fingerprint: Unrecognized Linux Firefox 128.0 (First seen 4 minutes ago)\n'
             'Velocity Check: 3 previous transactions attempted in past 10 minutes from Singapore (), London (), and Frankfurt (,850).\n'
             'Cardholder Typical Activity: Average monthly spend ,200. No prior cryptocurrency, wire transfer, or foreign cross-border '
             'transactions recorded in 3 years.\n'
             'Current Account Balance: ,200.00 USD.\n'
             'Two-Factor Authentication: SMS 2FA prompt bypassed via Session Hijacking / Cookie Injection anomaly.',
  'schema': {'is_fraudulent': {'type': 'boolean', 'description': 'Whether transaction is fraudulent'},
             'risk_tier': {'type': 'enum', 'description': 'Calculated risk tier', 'choices': ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']},
             'recommended_action': {'type': 'enum',
                                    'description': 'Immediate mitigation action',
                                    'choices': ['APPROVE', 'CHALLENGE_2FA', 'MANUAL_REVIEW', 'BLOCK_TRANSACTION', 'FREEZE_ACCOUNT']},
             'primary_anomaly': {'type': 'enum',
                                 'description': 'Predominant anomaly',
                                 'choices': ['IP_GEOLOCATION_MISMATCH',
                                             'UNUSUAL_VELOCITY',
                                             'HIGH_VALUE_TRANSFER',
                                             'NEW_DEVICE',
                                             'TOR_EXIT_NODE']},
             'secondary_anomaly': {'type': 'enum',
                                   'description': 'Secondary anomaly indicator',
                                   'choices': ['RAPID_DESTINATION_CHANGE', 'MULTIPLE_FAILED_LOGINS', 'CARD_NOT_PRESENT', 'NONE']},
             'requires_human_escalation': {'type': 'boolean', 'description': 'Whether senior fraud analyst must review'},
             'can_auto_block': {'type': 'boolean', 'description': 'Whether system should execute automated block'},
             'aml_sar_filing_required': {'type': 'boolean', 'description': 'Whether FinCEN SAR report must be filed'},
             'fincen_flag_threshold': {'type': 'boolean', 'description': 'Whether transfer amount exceeds AML reporting threshold'},
             'sanctions_screening_risk': {'type': 'enum',
                                          'description': 'OFAC sanctions risk',
                                          'choices': ['CLEARED', 'POTENTIAL_MATCH', 'HIGH_CONFIDENCE_MATCH']},
             'tor_exit_node_detected': {'type': 'boolean', 'description': 'Whether connection originates from anonymizing proxy/Tor'},
             'device_fingerprint_mismatch': {'type': 'boolean', 'description': 'Whether device hardware ID differs from cardholder device'},
             'velocity_score': {'type': 'enum',
                                'description': 'Transaction frequency score',
                                'choices': ['NORMAL', 'ELEVATED', 'EXTREME_BURST']},
             'block_card_immediately': {'type': 'boolean', 'description': 'Whether payment card should be deactivated immediately'},
             'freeze_online_banking': {'type': 'boolean', 'description': 'Whether web portal access should be restricted'},
             'notify_cardholder_sms': {'type': 'boolean', 'description': 'Whether urgent SMS alert should be dispatched'},
             'notify_cardholder_email': {'type': 'boolean', 'description': 'Whether notification email should be dispatched'},
             'requires_identity_verification': {'type': 'boolean',
                                                'description': 'Whether government ID biometric verification is required'},
             'merchant_category_risk': {'type': 'enum',
                                        'description': 'Merchant category code risk level',
                                        'choices': ['LOW', 'MODERATE', 'HIGH_RISK_CRYPTO', 'RESTRICTED_GAMBLING']},
             'chargeback_probability': {'type': 'enum',
                                        'description': 'Probability of cardholder chargeback dispute',
                                        'choices': ['LOW', 'MEDIUM', 'VERY_HIGH']},
             'counterparty_jurisdiction_risk': {'type': 'enum',
                                                'description': 'Jurisdiction risk tier of destination merchant',
                                                'choices': ['TIER_1_LOW', 'TIER_2_MODERATE', 'TIER_3_HIGH', 'SANCTIONED_ZONE']},
             'auto_reverse_transfer': {'type': 'boolean', 'description': 'Whether clearing network should attempt immediate reversal'},
             'fraud_ring_association': {'type': 'boolean', 'description': 'Whether signature matches known syndicate patterns'},
             'alert_clearing_house': {'type': 'boolean', 'description': 'Whether inter-bank network should be warned'},
             'escalate_to_fiu': {'type': 'boolean', 'description': 'Whether Financial Intelligence Unit should be notified'},
             'confidence_score_tier': {'type': 'enum',
                                       'description': 'Model decision confidence bucket',
                                       'choices': ['HIGH_CONFIDENCE_FRAUD', 'LEANING_FRAUD', 'BORDERLINE', 'LEGITIMATE']},
             'loss_prevention_priority': {'type': 'enum',
                                          'description': 'Queue priority for asset recovery team',
                                          'choices': ['IMMEDIATE_P0', 'STANDARD_QUEUE', 'LOW_PRIORITY']},
             'account_takeover_suspected': {'type': 'boolean', 'description': 'Whether cardholder credentials were compromised'}}},
 {'id': 'high_cardinality_255',
  'title': 'High-Cardinality 255-Choice Tariff & Customs Router',
  'description': 'Real-time multi-attribute classification featuring a 255-choice discrete enum to demonstrate non-degraded O(1) latency '
                 'scaling.',
  'context': 'CUSTOMS CLEARANCE INVOICE #AIR-60291\n'
             'Shipper: Precision AeroForgings GmbH, Stuttgart, Germany\n'
             'Consignee: Lockheed Skyworks Defense Facility, Fort Worth, TX, USA\n'
             'Item Description: Batch of 5,000 aerospace-grade titanium alloy hex-flange structural fasteners (Ti-6Al-4V Grade 5) with '
             'anodized dry-film anti-galling lubricant coating. Specifically milled and certified under Aerospace Standard AS9500 for '
             'turbine rotor assembly in commercial and defense propulsion modules.\n'
             'Gross Weight: 240 kg\n'
             'Declared Value: ,500 USD\n'
             'ITAR / Dual-Use Assessment: Requires verification of Defense Logistics Agency (DLA) end-user certificate.',
  'schema': {'customs_category': {'type': 'enum',
                                  'description': 'The exact Harmonized Tariff HS code category chosen from 255 international commodity '
                                                 'classes.',
                                  'choices': ['CAT_000_Live_Animals',
                                              'CAT_001_Meat_&_Edible_Offal',
                                              'CAT_002_Fish_&_Seafood',
                                              'CAT_003_Dairy_&_Birds_Eggs',
                                              'CAT_004_Animal_Origin_Products',
                                              'CAT_005_Live_Trees_&_Plants',
                                              'CAT_006_Edible_Vegetables',
                                              'CAT_007_Edible_Fruits_&_Nuts',
                                              'CAT_008_Coffee_&_Tea_Spices',
                                              'CAT_009_Cereals_&_Grains',
                                              'CAT_010_Milling_Industry_Products',
                                              'CAT_011_Oil_Seeds_&_Oleaginous',
                                              'CAT_012_Lac_Gums_&_Resins',
                                              'CAT_013_Vegetable_Plaiting_Materials',
                                              'CAT_014_Animal_&_Vegetable_Fats',
                                              'CAT_015_Meat_&_Fish_Preparations',
                                              'CAT_016_Sugars_&_Sugar_Confectionery',
                                              'CAT_017_Cocoa_&_Cocoa_Preparations',
                                              'CAT_018_Cereal_&_Flour_Preparations',
                                              'CAT_019_Vegetable_Preparations',
                                              'CAT_020_Beverages_Spirits_&_Vinegar',
                                              'CAT_021_Residues_&_Animal_Fodder',
                                              'CAT_022_Tobacco_&_Manufactured_Substitutes',
                                              'CAT_023_Salt_Sulfur_Earth_&_Stone',
                                              'CAT_024_Ores_Slag_&_Ash',
                                              'CAT_025_Mineral_Fuels_&_Mineral_Oils',
                                              'CAT_026_Inorganic_Chemicals_&_Compounds',
                                              'CAT_027_Organic_Chemicals',
                                              'CAT_028_Pharmaceutical_Products',
                                              'CAT_029_Fertilizers',
                                              'CAT_030_Tanning_or_Dyeing_Extracts',
                                              'CAT_031_Essential_Oils_&_Resinoids',
                                              'CAT_032_Soap_&_Lubricating_Preparations',
                                              'CAT_033_Albuminoidal_Substances_&_Glues',
                                              'CAT_034_Explosives_&_Pyrotechnic_Products',
                                              'CAT_035_Photographic_or_Cinematographic',
                                              'CAT_036_Miscellaneous_Chemical_Products',
                                              'CAT_037_Plastics_&_Articles_Thereof',
                                              'CAT_038_Rubber_&_Articles_Thereof',
                                              'CAT_039_Raw_Hides_&_Skins_&_Leather',
                                              'CAT_040_Leather_Articles_&_Saddlery',
                                              'CAT_041_Furskins_&_Artificial_Fur',
                                              'CAT_042_Wood_&_Articles_of_Wood',
                                              'CAT_043_Cork_&_Articles_of_Cork',
                                              'CAT_044_Manufactures_of_Straw_&_Esparto',
                                              'CAT_045_Pulp_of_Wood_or_Cellulosic',
                                              'CAT_046_Paper_&_Paperboard_Articles',
                                              'CAT_047_Printed_Books_&_Periodicals',
                                              'CAT_048_Silk_&_Woven_Fabrics',
                                              'CAT_049_Wool_&_Fine_Animal_Hair',
                                              'CAT_050_Cotton_&_Cotton_Fabrics',
                                              'CAT_051_Other_Vegetable_Textile_Fibers',
                                              'CAT_052_Man-Made_Filaments_&_Strip',
                                              'CAT_053_Man-Made_Staple_Fibers',
                                              'CAT_054_Wadding_Felt_&_Nonwovens',
                                              'CAT_055_Carpets_&_Textile_Floor_Coverings',
                                              'CAT_056_Special_Woven_Fabrics_&_Lace',
                                              'CAT_057_Impregnated_Coated_Textile_Fabrics',
                                              'CAT_058_Knitted_or_Crocheted_Fabrics',
                                              'CAT_059_Apparel_Articles_Knitted',
                                              'CAT_060_Apparel_Articles_Not_Knitted',
                                              'CAT_061_Other_Made_Up_Textile_Articles',
                                              'CAT_062_Footwear_Gaiters_&_Parts',
                                              'CAT_063_Headgear_&_Parts_Thereof',
                                              'CAT_064_Umbrellas_Walking_Sticks_&_Whips',
                                              'CAT_065_Prepared_Feathers_&_Down',
                                              'CAT_066_Articles_of_Stone_Plaster_Cement',
                                              'CAT_067_Ceramic_Products',
                                              'CAT_068_Glass_&_Glassware',
                                              'CAT_069_Natural_or_Cultured_Pearls_&_Gems',
                                              'CAT_070_Iron_&_Steel_Primary',
                                              'CAT_071_Articles_of_Iron_or_Steel',
                                              'CAT_072_Copper_&_Articles_Thereof',
                                              'CAT_073_Nickel_&_Articles_Thereof',
                                              'CAT_074_Aluminum_&_Articles_Thereof',
                                              'CAT_075_Lead_&_Articles_Thereof',
                                              'CAT_076_Zinc_&_Articles_Thereof',
                                              'CAT_077_Tin_&_Articles_Thereof',
                                              'CAT_078_Other_Base_Metals_&_Cermets',
                                              'CAT_079_Tools_Implements_Cutlery',
                                              'CAT_080_Miscellaneous_Articles_of_Base_Metal',
                                              'CAT_081_Nuclear_Reactors_Boilers_Machinery',
                                              'CAT_082_Electrical_Machinery_&_Equipment',
                                              'CAT_083_Railway_or_Tramway_Locomotives',
                                              'CAT_084_Vehicles_Other_Than_Railway',
                                              'CAT_085_Aircraft_Spacecraft_&_Parts',
                                              'CAT_086_Ships_Boats_&_Floating_Structures',
                                              'CAT_087_Optical_Photographic_Cinematographic',
                                              'CAT_088_Clocks_&_Watches_&_Parts',
                                              'CAT_089_Musical_Instruments_&_Parts',
                                              'CAT_090_Arms_&_Ammunition_&_Parts',
                                              'CAT_091_Furniture_Bedding_Mattresses',
                                              'CAT_092_Toys_Games_&_Sports_Requisites',
                                              'CAT_093_Miscellaneous_Manufactured_Articles',
                                              'CAT_094_Works_of_Art_Collectors_Pieces',
                                              'CAT_095_Aerospace_Titanium_Fasteners_&_Bolts',
                                              'CAT_096_Precision_CNC_Rotary_Turbines',
                                              'CAT_097_Inertial_Guidance_Gyroscopes',
                                              'CAT_098_Satellite_Telemetry_Transceivers',
                                              'CAT_099_Semiconductor_Lithography_Masks',
                                              'CAT_100_Live_Animals',
                                              'CAT_101_Meat_&_Edible_Offal',
                                              'CAT_102_Fish_&_Seafood',
                                              'CAT_103_Dairy_&_Birds_Eggs',
                                              'CAT_104_Animal_Origin_Products',
                                              'CAT_105_Live_Trees_&_Plants',
                                              'CAT_106_Edible_Vegetables',
                                              'CAT_107_Edible_Fruits_&_Nuts',
                                              'CAT_108_Coffee_&_Tea_Spices',
                                              'CAT_109_Cereals_&_Grains',
                                              'CAT_110_Milling_Industry_Products',
                                              'CAT_111_Oil_Seeds_&_Oleaginous',
                                              'CAT_112_Lac_Gums_&_Resins',
                                              'CAT_113_Vegetable_Plaiting_Materials',
                                              'CAT_114_Animal_&_Vegetable_Fats',
                                              'CAT_115_Meat_&_Fish_Preparations',
                                              'CAT_116_Sugars_&_Sugar_Confectionery',
                                              'CAT_117_Cocoa_&_Cocoa_Preparations',
                                              'CAT_118_Cereal_&_Flour_Preparations',
                                              'CAT_119_Vegetable_Preparations',
                                              'CAT_120_Beverages_Spirits_&_Vinegar',
                                              'CAT_121_Residues_&_Animal_Fodder',
                                              'CAT_122_Tobacco_&_Manufactured_Substitutes',
                                              'CAT_123_Salt_Sulfur_Earth_&_Stone',
                                              'CAT_124_Ores_Slag_&_Ash',
                                              'CAT_125_Mineral_Fuels_&_Mineral_Oils',
                                              'CAT_126_Inorganic_Chemicals_&_Compounds',
                                              'CAT_127_Organic_Chemicals',
                                              'CAT_128_Pharmaceutical_Products',
                                              'CAT_129_Fertilizers',
                                              'CAT_130_Tanning_or_Dyeing_Extracts',
                                              'CAT_131_Essential_Oils_&_Resinoids',
                                              'CAT_132_Soap_&_Lubricating_Preparations',
                                              'CAT_133_Albuminoidal_Substances_&_Glues',
                                              'CAT_134_Explosives_&_Pyrotechnic_Products',
                                              'CAT_135_Photographic_or_Cinematographic',
                                              'CAT_136_Miscellaneous_Chemical_Products',
                                              'CAT_137_Plastics_&_Articles_Thereof',
                                              'CAT_138_Rubber_&_Articles_Thereof',
                                              'CAT_139_Raw_Hides_&_Skins_&_Leather',
                                              'CAT_140_Leather_Articles_&_Saddlery',
                                              'CAT_141_Furskins_&_Artificial_Fur',
                                              'CAT_142_Wood_&_Articles_of_Wood',
                                              'CAT_143_Cork_&_Articles_of_Cork',
                                              'CAT_144_Manufactures_of_Straw_&_Esparto',
                                              'CAT_145_Pulp_of_Wood_or_Cellulosic',
                                              'CAT_146_Paper_&_Paperboard_Articles',
                                              'CAT_147_Printed_Books_&_Periodicals',
                                              'CAT_148_Silk_&_Woven_Fabrics',
                                              'CAT_149_Wool_&_Fine_Animal_Hair',
                                              'CAT_150_Cotton_&_Cotton_Fabrics',
                                              'CAT_151_Other_Vegetable_Textile_Fibers',
                                              'CAT_152_Man-Made_Filaments_&_Strip',
                                              'CAT_153_Man-Made_Staple_Fibers',
                                              'CAT_154_Wadding_Felt_&_Nonwovens',
                                              'CAT_155_Carpets_&_Textile_Floor_Coverings',
                                              'CAT_156_Special_Woven_Fabrics_&_Lace',
                                              'CAT_157_Impregnated_Coated_Textile_Fabrics',
                                              'CAT_158_Knitted_or_Crocheted_Fabrics',
                                              'CAT_159_Apparel_Articles_Knitted',
                                              'CAT_160_Apparel_Articles_Not_Knitted',
                                              'CAT_161_Other_Made_Up_Textile_Articles',
                                              'CAT_162_Footwear_Gaiters_&_Parts',
                                              'CAT_163_Headgear_&_Parts_Thereof',
                                              'CAT_164_Umbrellas_Walking_Sticks_&_Whips',
                                              'CAT_165_Prepared_Feathers_&_Down',
                                              'CAT_166_Articles_of_Stone_Plaster_Cement',
                                              'CAT_167_Ceramic_Products',
                                              'CAT_168_Glass_&_Glassware',
                                              'CAT_169_Natural_or_Cultured_Pearls_&_Gems',
                                              'CAT_170_Iron_&_Steel_Primary',
                                              'CAT_171_Articles_of_Iron_or_Steel',
                                              'CAT_172_Copper_&_Articles_Thereof',
                                              'CAT_173_Nickel_&_Articles_Thereof',
                                              'CAT_174_Aluminum_&_Articles_Thereof',
                                              'CAT_175_Lead_&_Articles_Thereof',
                                              'CAT_176_Zinc_&_Articles_Thereof',
                                              'CAT_177_Tin_&_Articles_Thereof',
                                              'CAT_178_Other_Base_Metals_&_Cermets',
                                              'CAT_179_Tools_Implements_Cutlery',
                                              'CAT_180_Miscellaneous_Articles_of_Base_Metal',
                                              'CAT_181_Nuclear_Reactors_Boilers_Machinery',
                                              'CAT_182_Electrical_Machinery_&_Equipment',
                                              'CAT_183_Railway_or_Tramway_Locomotives',
                                              'CAT_184_Vehicles_Other_Than_Railway',
                                              'CAT_185_Aircraft_Spacecraft_&_Parts',
                                              'CAT_186_Ships_Boats_&_Floating_Structures',
                                              'CAT_187_Optical_Photographic_Cinematographic',
                                              'CAT_188_Clocks_&_Watches_&_Parts',
                                              'CAT_189_Musical_Instruments_&_Parts',
                                              'CAT_190_Arms_&_Ammunition_&_Parts',
                                              'CAT_191_Furniture_Bedding_Mattresses',
                                              'CAT_192_Toys_Games_&_Sports_Requisites',
                                              'CAT_193_Miscellaneous_Manufactured_Articles',
                                              'CAT_194_Works_of_Art_Collectors_Pieces',
                                              'CAT_195_Aerospace_Titanium_Fasteners_&_Bolts',
                                              'CAT_196_Precision_CNC_Rotary_Turbines',
                                              'CAT_197_Inertial_Guidance_Gyroscopes',
                                              'CAT_198_Satellite_Telemetry_Transceivers',
                                              'CAT_199_Semiconductor_Lithography_Masks',
                                              'CAT_200_Live_Animals',
                                              'CAT_201_Meat_&_Edible_Offal',
                                              'CAT_202_Fish_&_Seafood',
                                              'CAT_203_Dairy_&_Birds_Eggs',
                                              'CAT_204_Animal_Origin_Products',
                                              'CAT_205_Live_Trees_&_Plants',
                                              'CAT_206_Edible_Vegetables',
                                              'CAT_207_Edible_Fruits_&_Nuts',
                                              'CAT_208_Coffee_&_Tea_Spices',
                                              'CAT_209_Cereals_&_Grains',
                                              'CAT_210_Milling_Industry_Products',
                                              'CAT_211_Oil_Seeds_&_Oleaginous',
                                              'CAT_212_Lac_Gums_&_Resins',
                                              'CAT_213_Vegetable_Plaiting_Materials',
                                              'CAT_214_Animal_&_Vegetable_Fats',
                                              'CAT_215_Meat_&_Fish_Preparations',
                                              'CAT_216_Sugars_&_Sugar_Confectionery',
                                              'CAT_217_Cocoa_&_Cocoa_Preparations',
                                              'CAT_218_Cereal_&_Flour_Preparations',
                                              'CAT_219_Vegetable_Preparations',
                                              'CAT_220_Beverages_Spirits_&_Vinegar',
                                              'CAT_221_Residues_&_Animal_Fodder',
                                              'CAT_222_Tobacco_&_Manufactured_Substitutes',
                                              'CAT_223_Salt_Sulfur_Earth_&_Stone',
                                              'CAT_224_Ores_Slag_&_Ash',
                                              'CAT_225_Mineral_Fuels_&_Mineral_Oils',
                                              'CAT_226_Inorganic_Chemicals_&_Compounds',
                                              'CAT_227_Organic_Chemicals',
                                              'CAT_228_Pharmaceutical_Products',
                                              'CAT_229_Fertilizers',
                                              'CAT_230_Tanning_or_Dyeing_Extracts',
                                              'CAT_231_Essential_Oils_&_Resinoids',
                                              'CAT_232_Soap_&_Lubricating_Preparations',
                                              'CAT_233_Albuminoidal_Substances_&_Glues',
                                              'CAT_234_Explosives_&_Pyrotechnic_Products',
                                              'CAT_235_Photographic_or_Cinematographic',
                                              'CAT_236_Miscellaneous_Chemical_Products',
                                              'CAT_237_Plastics_&_Articles_Thereof',
                                              'CAT_238_Rubber_&_Articles_Thereof',
                                              'CAT_239_Raw_Hides_&_Skins_&_Leather',
                                              'CAT_240_Leather_Articles_&_Saddlery',
                                              'CAT_241_Furskins_&_Artificial_Fur',
                                              'CAT_242_Wood_&_Articles_of_Wood',
                                              'CAT_243_Cork_&_Articles_of_Cork',
                                              'CAT_244_Manufactures_of_Straw_&_Esparto',
                                              'CAT_245_Pulp_of_Wood_or_Cellulosic',
                                              'CAT_246_Paper_&_Paperboard_Articles',
                                              'CAT_247_Printed_Books_&_Periodicals',
                                              'CAT_248_Silk_&_Woven_Fabrics',
                                              'CAT_249_Wool_&_Fine_Animal_Hair',
                                              'CAT_250_Cotton_&_Cotton_Fabrics',
                                              'CAT_251_Other_Vegetable_Textile_Fibers',
                                              'CAT_252_Man-Made_Filaments_&_Strip',
                                              'CAT_253_Man-Made_Staple_Fibers',
                                              'CAT_254_Wadding_Felt_&_Nonwovens']},
             'export_license_required': {'type': 'boolean',
                                         'description': 'Whether this item requires a specialized export/import defense trade license.'},
             'is_dual_use_goods': {'type': 'boolean',
                                   'description': 'Whether the goods qualify as dual-use (commercial and military applicability).'},
             'inspection_priority': {'type': 'enum',
                                     'description': 'Customs border inspection protocol tier.',
                                     'choices': ['STANDARD_FAST_TRACK', 'RANDOM_SCREENING', 'HOLD_PHYSICAL_LAB_INSPECTION']}}}]
